### ISSUE TITLE
Create Risk Management Process

### ISSUE THREAD

**Issue by KevDog** [KevDog/kevdog#2]
```[tasklist]
### Tasks
- [ ] https://github.com/KevDog/kevdog/issues/14
- [x] Define Time Horizons
- [x] Write Process
- [ ] https://github.com/KevDog/kevdog/issues/19
- [x] https://github.com/KevDog/kevdog/issues/20
- [ ] https://github.com/KevDog/kevdog/issues/15
- [ ] https://github.com/KevDog/kevdog/issues/16
```
