### ISSUE TITLE
Fix Execution Review

### ISSUE THREAD

**Issue by KevDog** [KevDog/kevdog#7]
```[tasklist]
### Tasks
- [x] Read Any Other Comments
- [x] Add a place to collect retro items
- [x] Install Risk Management Policy if desired
```
